services:
  app:
    build: .
    environment:
      JOB_EXPIRE_INTERVAL: 1000
      JOB_REQUEUE_INTERVAL: 1000
      DEFAULT_JOB_REQUEUE_LIMIT: -1
      ENABLE_REQUEUE_SCRIPT: "true"
      LOG_LEVEL: INFO
      REDIS_DB: 0
      REDIS_KEY_PREFIX: fq_server
      REDIS_CONN_TYPE: tcp_sock
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_CLUSTERED: "false"
    ports:
      - "8300:8300"
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
